"use client";

import Header from "@/components/Terms/Header";
import {Section,Main} from '@/types/sections'
import Content from "@/components/Terms/Content";
import OnThisPage from "@/components/Terms/OnThisPage";
import LastUpdate from "@/components/Terms/LastUpdate";

const mainparagraph: Main['mainparagraph'] = (
  <>
 <p className="text-gray-700 dark:text-zinc-200">
  Welcome to <a href="/">Nextjsshop</a> (the "Site"), operated by Nextjsshop ("Nextjsshop", "we", "us", and/or "our"). Nextjsshop provides a platform for accessing and purchasing templates and UI components (the "Services"). We value your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, handle, and disclose personal data on our platform.
</p>
<p className="text-gray-700 dark:text-zinc-200">
  We use your data to provide and improve our Services. By using our Services, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used here have the same meanings as in our Terms and Conditions.
</p>
<p className="text-gray-700 dark:text-zinc-200">
  Our Terms and Conditions ("Terms") govern all use of our Services, and together with this Privacy Policy, form your agreement with us ("Agreement").
</p>

  </>
)

const sections: Section[] = [
  {
    id: 'introduction',
    title: 'Introduction',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Welcome to <a href="/" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">Nextjsshop</a> (the "Site"), hosted by Nextjsshop ("Nextjsshop", "we", "us", and/or "our"). Nextjsshop provides a platform for buying and using website templates and components (the "Services"). We value your privacy and are dedicated to protecting your personal data. This Privacy Policy covers how we collect, handle, and disclose personal data on our Platform.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We use your data to provide and improve Service. By using our Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Our <a href="/legal/terms" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">Terms and Conditions</a> (“Terms”) govern all use of our Service and together with this Privacy Policy constitute your agreement with us (“Agreement”).
        </p>
      </>
    ),
  },
  {
    id: 'definitions',
    title: 'Definitions',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Below is a list of definitions for the terms used in this Privacy Policy:
        </p>
        <div className="max-w-screen overflow-scroll">
          <table className="w-full border-collapse">
            <thead>
              <tr className="bg-gray-100 dark:bg-zinc-800 transition-colors duration-300 ease-in-out">
                <th className="text-gray-800 dark:text-zinc-200 p-2 text-left">Term</th>
                <th className="text-gray-800 dark:text-zinc-200 p-2 text-left">Definition</th>
              </tr>
            </thead>
            <tbody>
              <tr className="bg-white dark:bg-[#09090B] transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>Service</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">nextjsshop website and related services operated by Nextjsshop.</td>
              </tr>
              <tr className="bg-gray-50 dark:bg-zinc-900 transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>Personal Data</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">Data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</td>
              </tr>
              <tr className="bg-white dark:bg-[#09090B] transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>Usage Data</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">Data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</td>
              </tr>
              <tr className="bg-gray-50 dark:bg-zinc-900 transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>Cookies</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">Small files stored on your device (computer or mobile device).</td>
              </tr>
              <tr className="bg-white dark:bg-[#09090B] transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>Data Controller</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">A natural or legal person who determines the purposes for which and the manner in which any personal data are processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</td>
              </tr>
              <tr className="bg-gray-50 dark:bg-zinc-900 transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>Data Processors (or Service Providers)</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">Any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers to process your data more effectively.</td>
              </tr>
              <tr className="bg-white dark:bg-[#09090B] transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>Data Subject</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">Any living individual who is the subject of Personal Data.</td>
              </tr>
              <tr className="bg-gray-50 dark:bg-zinc-900 transition-colors duration-300 ease-in-out">
                <td className="text-gray-700 dark:text-zinc-200 p-2"><strong>User</strong></td>
                <td className="text-gray-700 dark:text-zinc-200 p-2">The individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </>
    ),
  },
  {
    id: 'use-of-data',
    title: 'Use of Data',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Nextjsshop uses the collected data for various purposes:
        </p>
        <ul className="list-disc text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out" style={{ listStylePosition: 'outside', paddingLeft: '2rem' }}>
          <li>to provide and maintain our Service;</li>
          <li>to notify you about changes to our Service;</li>
          <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
          <li>to provide customer support;</li>
          <li>to gather analysis or valuable information so that we can improve our Service;</li>
          <li>to monitor the usage of our Service;</li>
          <li>to detect, prevent and address technical issues;</li>
          <li>to fulfill any other purpose for which you provide it;</li>
          <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
          <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
          <li>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
          <li>in any other way we may describe when you provide the information;</li>
          <li>for any other purpose with your consent.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'retention-of-data',
    title: 'Retention of Data',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
        </p>
      </>
    ),
  },
  {
    id: 'transfer-of-data',
    title: 'Transfer of Data',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Nextjsshop will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
        </p>
      </>
    ),
  },
  {
    id: 'disclosure-of-data',
    title: 'Disclosure of Data',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We may disclose personal information that we collect, or you provide:
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out"><strong>Disclosure for Law Enforcement</strong></p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out"><strong>Business Transaction</strong></p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out"><strong>Other cases</strong></p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We may disclose your information also:
        </p>
        <ul className="list-disc text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out" style={{ listStylePosition: 'outside', paddingLeft: '2rem' }}>
          <li>to our subsidiaries and affiliates;</li>
          <li>to contractors, service providers, and other third parties we use to support our business;</li>
          <li>to fulfill the purpose for which you provide it;</li>
          <li>for the purpose of including your company’s logo on our website;</li>
          <li>for any other purpose disclosed by us when you provide the information;</li>
          <li>with your consent in any other cases;</li>
          <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
        </ul>
      </>
    ),
  },
  
  {
    id: 'security-of-data',
    title: 'Security of Data',
    content: (
      <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
        The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
      </p>
    ),
  },
  {
    id: 'your-data-protection-rights-under-general-data-protection-regulation-gdpr',
    title: 'Your Data Protection Rights Under General Data Protection Regulation (GDPR)',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by <a target="_blank" rel="noopener noreferrer" href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">GDPR</a>.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <a href="/contact/support" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">support@nextjsshop.com</a>.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          In certain circumstances, you have the following data protection rights:
        </p>
        <ul className="list-disc text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out" style={{ listStylePosition: 'outside', paddingLeft: '2rem' }}>
          <li>the right to access, update or to delete the information we have on you;</li>
          <li>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
          <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
          <li>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
          <li>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
          <li>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
        </ul>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide the Service without some necessary data.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
        </p>
      </>
    ),
  },
  {
    id: 'your-data-protection-rights-under-the-california-privacy-protection-act-caloppa',
    title: 'Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. <a target="_blank" rel="noopener noreferrer" href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">Read more here</a>.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          According to CalOPPA we agree to the following:
        </p>
        <ul className="list-disc text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out" style={{ listStylePosition: 'outside', paddingLeft: '2rem' }}>
          <li>users can visit our site anonymously;</li>
          <li>our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website;</li>
          <li>users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
          <li>users are able to change their personal information by emailing us at <a href="/contact/support" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">support@nextjsshop.com</a>;</li>
          <li>Our Policy on “Do Not Track” Signals:</li>
        </ul>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
        </p>
      </>
    ),
  },
  
  {
    id: 'your-data-protection-rights-under-the-california-consumer-privacy-act-ccpa',
    title: 'Your Data Protection Rights under the California Consumer Privacy Act (CCPA)',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          What personal information we have about you. If you make this request, we will return to you:
        </p>
        <ul className="list-disc text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out" style={{ listStylePosition: 'outside', paddingLeft: '2rem' }}>
          <li>The categories of personal information we have collected about you.</li>
          <li>The categories of sources from which we collect your personal information.</li>
          <li>The business or commercial purpose for collecting or selling your personal information.</li>
          <li>The categories of third parties with whom we share personal information.</li>
          <li>The specific pieces of personal information we have collected about you.</li>
          <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
          <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
        </ul>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          To stop selling your personal information. We don't sell or rent your personal information to any third parties for any purpose. You are the only owner of your Personal Data and can request disclosure or deletion at any time.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          To exercise your California data protection rights described above, please send your request(s) to <a href="/contact/support" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">support@nextjsshop.com</a>.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
        </p>
      </>
    ),
  },
  {
    id: 'links-to-other-sites',
    title: 'Links to Other Sites',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>
      </>
    ),
  },
  {
    id: 'changes-to-this-privacy-policy',
    title: 'Changes to This Privacy Policy',
    content: (
      <>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy.
        </p>
        <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
      </>
    ),
  },
  {
    id: 'contact-us',
    title: 'Contact Us',
    content: (
      <p className="text-gray-700 dark:text-zinc-200 transition-colors duration-300 ease-in-out">
        If you have any questions about this Privacy Policy, please contact us at{' '}
        <a href="/contact/support" className="text-neutral-500 dark:text-zinc-400 hover:text-black dark:hover:text-zinc-100 transition-colors duration-300 ease-in-out">
          support@nextjsshop.com
        </a>.
      </p>
    ),
  },
  
];

export default function PrivacyPolicy() {
  return (
     <div className="max-w-[1240px] mx-auto ">
      <div className="relative z-10">
        <Header title="Privacy Policy" />
      </div>
      <div className="grid-section relative overflow-clip px-4 border-grid-border [.grid-section_~_&]:border-t-0 border-y">
        <div className="relative z-0 mx-auto max-w-grid-width border-grid-border border-x">
          <div className="relative grid grid-cols-4 gap-10 bg-white dark:bg-[#09090B] p-8 sm:p-12 lg:gap-20">
           <Content sections={sections} mainparagraph={mainparagraph}/>
            <div className="hidden md:block">
              <OnThisPage sections={sections} />
            </div>
          </div>
        </div>
      </div>
      <div className="max-w-[1208px] mx-auto ">
      <LastUpdate />
      </div>
    </div>
  );
} 